#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Create a GitHub Pull Request for a DocSync SDLC test case implementation.

.DESCRIPTION
    Uses the GitHub REST API to:
      1. Create a feature branch from main
      2. Push source files for the test case
      3. Open a Pull Request with the PR description from the docs folder

    Required environment variables:
      GITHUB_TOKEN              â€” Personal Access Token with repo scope
      GITHUB_REPOSITORY_OWNER  â€” GitHub org or username
      GITHUB_REPOSITORY_NAME   â€” Repository name

.EXAMPLE
    scripts\create-github-pr.ps1 -TestCase TC-003
    scripts\create-github-pr.ps1 -TestCase TC-003 -BaseBranch develop
    scripts\create-github-pr.ps1 -TestCase TC-003 -DryRun
#>

param(
    [Parameter(Mandatory)]
    [string]$TestCase,

    [string]$BaseBranch = "main",
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = Split-Path $PSScriptRoot -Parent

# â”€â”€ Load credentials from environment (never hardcode) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$Token = $env:GITHUB_TOKEN
$Owner = $env:GITHUB_REPOSITORY_OWNER
$Repo  = $env:GITHUB_REPOSITORY_NAME

if (-not $Token -or -not $Owner -or -not $Repo) {
    Write-Error @"
Missing required environment variables.
Set the following before running:
  GITHUB_TOKEN             â€” GitHub Personal Access Token (repo scope)
  GITHUB_REPOSITORY_OWNER â€” GitHub owner/organisation
  GITHUB_REPOSITORY_NAME  â€” Repository name
"@
    exit 1
}

$ApiBase    = "https://api.github.com"
$AuthHeader = @{
    Authorization = "Bearer $Token"
    Accept        = "application/vnd.github+json"
    "X-GitHub-Api-Version" = "2022-11-28"
}

$FeatureBranch = "docsync/$TestCase-implementation"

# â”€â”€ Load phase-status for user story â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$phaseStatusFile = Join-Path $Root "outputs\$TestCase\phase-status.json"
$userStory = "DocSync $TestCase implementation"
if (Test-Path $phaseStatusFile) {
    $phaseStatus = Get-Content $phaseStatusFile -Raw | ConvertFrom-Json
    if ($phaseStatus.user_story) { $userStory = $phaseStatus.user_story }
}

# Short title from user story (strip US-XXX: prefix)
$shortTitle = $userStory -replace '^US-\d+:\s*', '' -replace '^As a [^,]+,\s*I want\s*', '' 
if ($shortTitle.Length -gt 72) { $shortTitle = $shortTitle.Substring(0, 72) + "â€¦" }

# â”€â”€ Load PR description â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$prDescFile = Join-Path $Root "docs\$TestCase\pr-description.md"
$prBody     = if (Test-Path $prDescFile) { Get-Content $prDescFile -Raw } else {
    "## $TestCase â€” Implementation`n`n$userStory`n`n---`n_Generated by DocSync SDLC Pipeline_"
}

# â”€â”€ Helper: GitHub API call â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function Invoke-GitHub([string]$method, [string]$path, [hashtable]$body = @{}) {
    $url = "$ApiBase$path"
    $params = @{ Uri = $url; Method = $method; Headers = $AuthHeader }
    if ($method -ne "GET" -and $body.Count -gt 0) {
        $params["Body"]        = $body | ConvertTo-Json -Depth 10
        $params["ContentType"] = "application/json"
    }
    return Invoke-RestMethod @params
}

# â”€â”€ Step 1: Get base branch SHA â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
Write-Host ""
Write-Host "  Creating GitHub Pull Request" -ForegroundColor Cyan
Write-Host "  Repo    : $Owner/$Repo" -ForegroundColor White
Write-Host "  TC      : $TestCase" -ForegroundColor White
Write-Host "  Branch  : $FeatureBranch â†’ $BaseBranch" -ForegroundColor White
if ($DryRun) { Write-Host "  DRY RUN â€” no writes to GitHub" -ForegroundColor Yellow }
Write-Host ""

if ($DryRun) {
    Write-Host "  [dry] Would create branch: $FeatureBranch" -ForegroundColor DarkGray
    Write-Host "  [dry] Would create PR: [$TestCase] $shortTitle" -ForegroundColor DarkGray
    Write-Host ""
    exit 0
}

# Get base branch ref
$baseRef = Invoke-GitHub "GET" "/repos/$Owner/$Repo/git/ref/heads/$BaseBranch"
$baseSha  = $baseRef.object.sha
Write-Host "  Base SHA: $($baseSha.Substring(0,8))" -ForegroundColor DarkGray

# â”€â”€ Step 2: Create or verify feature branch â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$branchExists = $false
try {
    Invoke-GitHub "GET" "/repos/$Owner/$Repo/git/ref/heads/$FeatureBranch" | Out-Null
    $branchExists = $true
    Write-Host "  [~] Branch already exists: $FeatureBranch" -ForegroundColor Yellow
} catch {
    # Branch does not exist â€” create it
}

if (-not $branchExists) {
    Invoke-GitHub "POST" "/repos/$Owner/$Repo/git/refs" @{
        ref = "refs/heads/$FeatureBranch"
        sha = $baseSha
    } | Out-Null
    Write-Host "  [+] Created branch: $FeatureBranch" -ForegroundColor Green
}

# â”€â”€ Step 3: Push source files via git (uses local git, token in URL) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# We use git directly so we don't need to base64-encode every file via the API.
Write-Host "  [>] Pushing source files..." -ForegroundColor White

Push-Location $Root
try {
    $remoteWithToken = "https://$Token@github.com/$Owner/$Repo.git"

    # Ensure we have the remote and the feature branch locally
    $gitRemote = git remote get-url origin 2>$null
    if (-not $gitRemote) {
        git remote add origin $remoteWithToken 2>&1 | Out-Null
    }

    # Fetch and checkout the feature branch
    git fetch origin "$FeatureBranch" 2>&1 | Out-Null
    $checkoutResult = git checkout $FeatureBranch 2>&1
    if ($LASTEXITCODE -ne 0) {
        git checkout -b $FeatureBranch 2>&1 | Out-Null
    }

    # Stage implementation files
    git add src/docsync/ 2>&1 | Out-Null
    git add tests/ 2>&1 | Out-Null
    git add "docs/$TestCase/" 2>&1 | Out-Null

    $commitMsg = "feat($TestCase): $shortTitle`n`nImplements: $userStory`nAll 8 SDLC phases approved. Test case: $TestCase"

    $statusOutput = git status --porcelain 2>&1
    if ($statusOutput) {
        git commit -m $commitMsg 2>&1 | Out-Null
        git push $remoteWithToken "HEAD:$FeatureBranch" 2>&1 | Out-Null
        Write-Host "  [+] Files pushed to $FeatureBranch" -ForegroundColor Green
    } else {
        Write-Host "  [=] No changes to push (working tree clean)" -ForegroundColor DarkGray
    }

    # Return to original branch
    git checkout $BaseBranch 2>&1 | Out-Null
} finally {
    Pop-Location
}

# â”€â”€ Step 4: Check for existing PR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$existingPRs = Invoke-GitHub "GET" "/repos/$Owner/$Repo/pulls?head=${Owner}:${FeatureBranch}&state=open"
if ($existingPRs.Count -gt 0) {
    $pr = $existingPRs[0]
    Write-Host ""
    Write-Host "  [~] PR already exists:" -ForegroundColor Yellow
    Write-Host "      $($pr.html_url)" -ForegroundColor Cyan
    Write-Host ""
    exit 0
}

# â”€â”€ Step 5: Create PR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$pr = Invoke-GitHub "POST" "/repos/$Owner/$Repo/pulls" @{
    title = "[$TestCase] $shortTitle"
    body  = $prBody
    head  = $FeatureBranch
    base  = $BaseBranch
    draft = $false
}

# â”€â”€ Summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
Write-Host ""
Write-Host "  Pull Request Created" -ForegroundColor Green
Write-Host "  Title  : $($pr.title)" -ForegroundColor White
Write-Host "  Branch : $FeatureBranch â†’ $BaseBranch" -ForegroundColor White
Write-Host "  URL    : $($pr.html_url)" -ForegroundColor Cyan
Write-Host "  Number : #$($pr.number)" -ForegroundColor DarkGray
Write-Host ""

